-- Your SQL goes here

CREATE TABLE comments (
  id SERIAL PRIMARY KEY,
  body TEXT NOT NULL,
  user_id SERIAL NOT NULL,
  approved BOOLEAN NOT NULL DEFAULT 'f',
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)
