-- Your SQL goes here

CREATE TABLE comments (
  id SERIAL PRIMARY KEY,
  body TEXT NOT NULL,
  user_id SERIAL NOT NULL,
  post_url VARCHAR NOT NULL,
  approved BOOLEAN NOT NULL DEFAULT 't',
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  last_edit TIMESTAMP DEFAULT NULL
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  access_token VARCHAR NOT NULL,
  id_token VARCHAR NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  provider VARCHAR NOT NULL
)
